# Generated by Django 5.1.3 on 2024-11-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('road', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.road')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('sacco', models.ManyToManyField(to='stages.sacco')),
                ('route', models.ManyToManyField(to='stages.stops')),
            ],
        ),
        migrations.AddField(
            model_name='sacco',
            name='route',
            field=models.ManyToManyField(to='stages.stops'),
        ),
    ]
