# Generated by Django 5.1.3 on 2024-11-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stops',
            new_name='Stop',
        ),
    ]
