# Generated by Django 5.1.3 on 2024-11-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_rename_stops_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sacco',
            name='route',
        ),
    ]
